schema_version: 1

context:
  version: "1.8.0"

package:
  name: watertap
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/w/watertap/watertap-${{ version }}.tar.gz
  sha256: f64776ce506592ffea3439789998f38723a2f5340aab6bfd927e161655995742

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - pip
  run:
    - python >=${{ python_min }}
    - idaes-pse
    - pyomo
    - watertap-solvers
    - pyyaml
    - parameter-sweep
    - numpy
    - pint <0.25
    - reaktoro

tests:
  - python:
      imports:
        - watertap
        - watertap.core.solvers
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: WaterTAP modeling library
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
  homepage: https://www.nawihub.org/knowledge/watertap
  repository: https://github.com/watertap-org/watertap
  documentation: https://watertap.readthedocs.io

extra:
  recipe-maintainers:
    - ksbeattie
    - sufikaur
